plugin:
  prefix: "[CozyLib]"
  command_prefix: "cozy"

mysql:
  host: localhost
  port: 3306
  username: root
  password: root
  database: cozylib

redis:
  host: 127.0.0.1
  port: 6379
  username: default
  password: password
  ssl: false

modules:
  messages: true
  sqlite: true
  mysql: true
  redis: false

integrations:
  world_guard: false
  excellent_economy: false
  skins_restorer: false
  better_model: false
  packet_events: false