name: CozyLib
version: '1.21.10-1'
main: asia.virtualmc.cozylib.CozyLib
api-version: '1.21'

softdepend:
  - BetterModel
  - Vault
  - WorldGuard
  - SkinsRestorer
  - RealisticSeasons
  - PlaceholderAPI
  - HologramLib